# Python CircleCI 2.0 configuration file
version: 2
jobs:
  test_site:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run tests
          command: python test.py
workflows:
  version: 2
  build_and_test:
    jobs:
      - test_site

